"""SmartForge data models.

Split into domain modules but re-exported here so existing imports
(`from app.models import X`) and Alembic's `from app.models import SQLModel`
keep working. Importing this package registers every SQLModel table with the
shared metadata before the DB engine is used.
"""

from sqlmodel import SQLModel  # re-exported for Alembic target_metadata

from app.models.audit import (
    AuditLog,
    AuditLogPublic,
    AuditLogsPublic,
)
from app.models.base import (
    Message,
    NewPassword,
    Token,
    TokenPayload,
    get_datetime_utc,
)
from app.models.customer import (
    Customer,
    CustomerCreate,
    CustomerMessage,
    CustomerMessagePublic,
    CustomerOrder,
    CustomerOrderCreate,
    CustomerOrderPublic,
    CustomerOrdersPublic,
    CustomerPublic,
    Escalation,
    EscalationCreate,
    EscalationPublic,
    EscalationsPublic,
    EscalationStatus,
    HumanResponse,
    OrderStage,
)
from app.models.factory import (
    FactoriesPublic,
    Factory,
    FactoryCreate,
    FactoryPublic,
    Line,
    LineCreate,
    LinePublic,
    LinesPublic,
    LineStatus,
    Machine,
    MachineCreate,
    MachinePublic,
    MachinesPublic,
    MachineStatus,
    MachineType,
    MachineUpdate,
    MaintenanceState,
)
from app.models.integration import (
    ErpSyncEvent,
    IntegrationsStatusPublic,
    IntegrationStatus,
    MesSyncEvent,
    SyncDirection,
    SyncEventPublic,
    SyncEventsPublic,
    SyncStatus,
)
from app.models.item import (
    Item,
    ItemBase,
    ItemCreate,
    ItemPublic,
    ItemsPublic,
    ItemUpdate,
)
from app.models.knowledge import (
    AskaiSession,
    AskaiSessionPublic,
    AskRequest,
    AskResponse,
    DocumentKind,
    ForgeResponse,
    KnowledgeBase,
    KnowledgeBaseCreate,
    KnowledgeBasePublic,
    KnowledgeBasesPublic,
    KnowledgeBaseUpdate,
    KnowledgeDocument,
    KnowledgeDocumentCreate,
    KnowledgeDocumentPublic,
    KnowledgeDocumentsPublic,
    SimFocus,
    SourceRef,
)
from app.models.maintenance import (
    Alert,
    AlertPublic,
    AlertsPublic,
    AlertStatus,
    FiixSyncState,
    Incident,
    IncidentCreate,
    IncidentPublic,
    IncidentsPublic,
    RcaRecord,
    RcaRecordCreate,
    RcaRecordPublic,
    RcaRecordsPublic,
    Severity,
    WorkOrder,
    WorkOrderCreate,
    WorkOrderPublic,
    WorkOrdersPublic,
    WorkOrderStatus,
)
from app.models.maintenance_ticket import (
    MaintenanceTicket,
    MaintenanceTicketDetail,
    MaintenanceTicketLog,
    MaintenanceTicketPart,
    MaintenanceTicketPublic,
    MaintenanceTicketsPublic,
    TicketAcknowledge,
    TicketLogPublic,
    TicketNote,
    TicketPartPublic,
    TicketReference,
    TicketStatusUpdate,
)
from app.models.optimization import (
    MachineConfiguration,
    MachineConfigurationCreate,
    MachineConfigurationPublic,
    MachineConfigurationsPublic,
    Recommendation,
    RecommendationCreate,
    RecommendationPublic,
    RecommendationsPublic,
    RecommendationStatus,
)
from app.models.production import (
    Job,
    JobCreate,
    JobPublic,
    JobsPublic,
    JobStatus,
    OeeMetric,
    OeeMetricPublic,
    OeeMetricsPublic,
    ProductionRun,
    ProductionRunCreate,
    ProductionRunPublic,
    ProductionRunsPublic,
)
from app.models.quality import (
    Defect,
    DefectCreate,
    DefectPublic,
    DefectsPublic,
    Inspection,
    InspectionCreate,
    InspectionPublic,
    InspectionsPublic,
)
from app.models.reorder import (
    MaterialReorder,
    MaterialReorderPublic,
    MaterialReordersPublic,
    ReorderActionRequest,
)
from app.models.sop import (
    Sop,
    SopDetailPublic,
    SopPublic,
    SopSection,
    SopSectionPublic,
    SopsPublic,
    SopUpdate,
)
from app.models.supply_chain import (
    InventoryItem,
    InventoryItemCreate,
    InventoryItemPublic,
    InventoryItemsPublic,
    PurchaseOrder,
    PurchaseOrderCreate,
    PurchaseOrderPublic,
    PurchaseOrdersPublic,
    PurchaseOrderStatus,
    Quote,
    QuoteCreate,
    QuotePublic,
    QuotesPublic,
    QuoteStatus,
    Supplier,
    SupplierCreate,
    SupplierPublic,
    SuppliersPublic,
    SupplierStatus,
)
from app.models.telemetry import (
    MachineHealthScore,
    MachineHealthScorePublic,
    MachineHealthScoresPublic,
    TelemetryEvent,
    TelemetryEventCreate,
    TelemetryEventPublic,
    TelemetryEventsPublic,
)
from app.models.user import (
    UpdatePassword,
    User,
    UserBase,
    UserCreate,
    UserPublic,
    UserRegister,
    UserRole,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    "SQLModel",
    "get_datetime_utc",
    "Message",
    "Token",
    "TokenPayload",
    "NewPassword",
    # user / item
    "User",
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UpdatePassword",
    "UserPublic",
    "UsersPublic",
    "UserRole",
    "Item",
    "ItemBase",
    "ItemCreate",
    "ItemUpdate",
    "ItemPublic",
    "ItemsPublic",
    # factory
    "Factory",
    "FactoryCreate",
    "FactoryPublic",
    "FactoriesPublic",
    "Line",
    "LineCreate",
    "LinePublic",
    "LinesPublic",
    "LineStatus",
    "Machine",
    "MachineCreate",
    "MachineUpdate",
    "MachinePublic",
    "MachinesPublic",
    "MachineStatus",
    "MachineType",
    "MaintenanceState",
    # telemetry
    "TelemetryEvent",
    "TelemetryEventCreate",
    "TelemetryEventPublic",
    "TelemetryEventsPublic",
    "MachineHealthScore",
    "MachineHealthScorePublic",
    "MachineHealthScoresPublic",
    # maintenance
    "Alert",
    "AlertPublic",
    "AlertsPublic",
    "AlertStatus",
    "Severity",
    "WorkOrder",
    "WorkOrderCreate",
    "WorkOrderPublic",
    "WorkOrdersPublic",
    "WorkOrderStatus",
    "FiixSyncState",
    "Incident",
    "IncidentCreate",
    "IncidentPublic",
    "IncidentsPublic",
    "RcaRecord",
    "RcaRecordCreate",
    "RcaRecordPublic",
    "RcaRecordsPublic",
    # material reorders
    "MaterialReorder",
    "MaterialReorderPublic",
    "MaterialReordersPublic",
    "ReorderActionRequest",
    # maintenance tickets
    "MaintenanceTicket",
    "MaintenanceTicketLog",
    "MaintenanceTicketPart",
    "MaintenanceTicketPublic",
    "MaintenanceTicketsPublic",
    "MaintenanceTicketDetail",
    "TicketPartPublic",
    "TicketLogPublic",
    "TicketAcknowledge",
    "TicketNote",
    "TicketStatusUpdate",
    "TicketReference",
    # sops
    "Sop",
    "SopSection",
    "SopPublic",
    "SopSectionPublic",
    "SopDetailPublic",
    "SopsPublic",
    "SopUpdate",
    # production
    "Job",
    "JobCreate",
    "JobPublic",
    "JobsPublic",
    "JobStatus",
    "ProductionRun",
    "ProductionRunCreate",
    "ProductionRunPublic",
    "ProductionRunsPublic",
    "OeeMetric",
    "OeeMetricPublic",
    "OeeMetricsPublic",
    # quality
    "Inspection",
    "InspectionCreate",
    "InspectionPublic",
    "InspectionsPublic",
    "Defect",
    "DefectCreate",
    "DefectPublic",
    "DefectsPublic",
    # optimization
    "MachineConfiguration",
    "MachineConfigurationCreate",
    "MachineConfigurationPublic",
    "MachineConfigurationsPublic",
    "Recommendation",
    "RecommendationCreate",
    "RecommendationPublic",
    "RecommendationsPublic",
    "RecommendationStatus",
    # integration
    "ErpSyncEvent",
    "MesSyncEvent",
    "SyncDirection",
    "SyncStatus",
    "SyncEventPublic",
    "SyncEventsPublic",
    "IntegrationStatus",
    "IntegrationsStatusPublic",
    # supply chain
    "Supplier",
    "SupplierCreate",
    "SupplierPublic",
    "SuppliersPublic",
    "SupplierStatus",
    "InventoryItem",
    "InventoryItemCreate",
    "InventoryItemPublic",
    "InventoryItemsPublic",
    "PurchaseOrder",
    "PurchaseOrderCreate",
    "PurchaseOrderPublic",
    "PurchaseOrdersPublic",
    "PurchaseOrderStatus",
    "Quote",
    "QuoteCreate",
    "QuotePublic",
    "QuotesPublic",
    "QuoteStatus",
    # customer
    "Customer",
    "CustomerCreate",
    "CustomerPublic",
    "CustomerOrder",
    "CustomerOrderCreate",
    "CustomerOrderPublic",
    "CustomerOrdersPublic",
    "OrderStage",
    "CustomerMessage",
    "CustomerMessagePublic",
    "Escalation",
    "EscalationCreate",
    "EscalationPublic",
    "EscalationsPublic",
    "EscalationStatus",
    "HumanResponse",
    # knowledge / askai
    "KnowledgeDocument",
    "KnowledgeDocumentCreate",
    "KnowledgeDocumentPublic",
    "KnowledgeDocumentsPublic",
    "KnowledgeBase",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBasePublic",
    "KnowledgeBasesPublic",
    "DocumentKind",
    "AskaiSession",
    "AskaiSessionPublic",
    "AskRequest",
    "AskResponse",
    "ForgeResponse",
    "SimFocus",
    "SourceRef",
    # audit
    "AuditLog",
    "AuditLogPublic",
    "AuditLogsPublic",
]
