// This file is auto-generated by @hey-api/openapi-ts

export type AlertPublic = {
    machine_id: string;
    rule: string;
    severity?: Severity;
    message: string;
    recommended_action?: (string | null);
    suggested_window?: (string | null);
    id: string;
    status: AlertStatus;
    acknowledged_at?: (string | null);
    resolved_at?: (string | null);
    created_at?: (string | null);
};

export type AlertsPublic = {
    data: Array<AlertPublic>;
    count: number;
};

export type AlertStatus = 'active' | 'acknowledged' | 'resolved';

export type AskaiSessionPublic = {
    user_id?: (string | null);
    machine_id?: (string | null);
    title?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type AskRequest = {
    question: string;
    session_id?: (string | null);
    machine_id?: (string | null);
};

export type AskResponse = {
    answer: string;
    sources?: Array<SourceRef>;
    suggested_actions?: Array<(string)>;
    confidence?: number;
    session_id?: (string | null);
};

export type Body_datasources_import_snapshot = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CustomerOrderPublic = {
    id: string;
    order_number: string;
    part_type: string;
    quantity: number;
    stage: OrderStage;
    estimated_completion?: (string | null);
    delayed?: boolean;
    delay_reason?: (string | null);
    created_at?: (string | null);
};

export type CustomerOrdersPublic = {
    data: Array<CustomerOrderPublic>;
    count: number;
};

export type DefectPublic = {
    inspection_id?: (string | null);
    line_id?: (string | null);
    defect_type: string;
    part_id?: (string | null);
    scrap_cost?: number;
    rework_cost?: number;
    is_scrap?: boolean;
    is_rework?: boolean;
    id: string;
    created_at?: (string | null);
};

export type DefectsPublic = {
    data: Array<DefectPublic>;
    count: number;
};

/**
 * Summary of a persisted discovery plan awaiting operator review; nothing
 * is seeded until this plan's fingerprint is explicitly confirmed.
 */
export type DiscoveryResponse = {
    plan_id: string;
    fingerprint: string;
    seedable: boolean;
    blocking_issues: Array<(string)>;
    table_count: number;
};

export type DocumentKind = 'manual' | 'sop' | 'troubleshooting' | 'machine_doc' | 'fault_note';

export type EscalationCreate = {
    order_id?: (string | null);
    question: string;
    ai_confidence?: number;
    reason?: (string | null);
};

export type EscalationPublic = {
    customer_id: string;
    order_id?: (string | null);
    question: string;
    ai_confidence?: number;
    reason?: (string | null);
    assigned_team?: (string | null);
    id: string;
    status: EscalationStatus;
    original_ai_answer?: (string | null);
    human_response?: (string | null);
    created_at?: (string | null);
};

export type EscalationsPublic = {
    data: Array<EscalationPublic>;
    count: number;
};

export type EscalationStatus = 'open' | 'assigned' | 'resolved';

export type FactoriesPublic = {
    data: Array<FactoryPublic>;
    count: number;
};

export type FactoryPublic = {
    name: string;
    location?: (string | null);
    timezone?: string;
    id: string;
    created_at?: (string | null);
};

export type FiixSyncState = 'not_synced' | 'pending' | 'synced' | 'failed';

/**
 * ForgeAI simulation-assistant answer + machine ids to highlight in-scene
 * and a cinematic focus directive for the simulation camera.
 */
export type ForgeResponse = {
    answer: string;
    sources?: Array<SourceRef>;
    suggested_actions?: Array<(string)>;
    confidence?: number;
    session_id?: (string | null);
    highlight?: Array<(string)>;
    focus?: (SimFocus | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HumanResponse = {
    human_response: string;
    assigned_team?: (string | null);
};

export type IncidentCreate = {
    title: string;
    factory_id: string;
    affected_machines?: (string | null);
    affected_jobs?: (string | null);
    delayed_orders?: number;
    downtime_minutes?: number;
    estimated_cost?: number;
    severity?: Severity;
};

export type IncidentPublic = {
    title: string;
    factory_id: string;
    affected_machines?: (string | null);
    affected_jobs?: (string | null);
    delayed_orders?: number;
    downtime_minutes?: number;
    estimated_cost?: number;
    severity?: Severity;
    id: string;
    resolved: boolean;
    created_at?: (string | null);
};

export type IncidentsPublic = {
    data: Array<IncidentPublic>;
    count: number;
};

export type InspectionCreate = {
    part_id: string;
    image_reference?: (string | null);
    defect_detected?: boolean;
    defect_type?: (string | null);
    confidence?: number;
    line_id?: (string | null);
};

export type InspectionPublic = {
    part_id: string;
    image_reference?: (string | null);
    defect_detected?: boolean;
    defect_type?: (string | null);
    confidence?: number;
    line_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type InspectionsPublic = {
    data: Array<InspectionPublic>;
    count: number;
};

export type IntegrationsStatusPublic = {
    erp: IntegrationStatus;
    mes: IntegrationStatus;
};

export type IntegrationStatus = {
    system: string;
    connected: boolean;
    last_successful_sync?: (string | null);
    failed_records?: number;
    total_events?: number;
};

export type InventoryItemPublic = {
    sku: string;
    name: string;
    material_type?: (string | null);
    quantity?: number;
    unit?: string;
    reorder_threshold?: number;
    supplier_id?: (string | null);
    factory_id?: (string | null);
    id: string;
    created_at?: (string | null);
    below_threshold?: boolean;
};

export type InventoryItemsPublic = {
    data: Array<InventoryItemPublic>;
    count: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobCreate = {
    customer: string;
    part_type: string;
    quantity?: number;
    due_date?: (string | null);
    required_materials?: (string | null);
    priority?: number;
    special_instructions?: (string | null);
    factory_id?: (string | null);
    customer_order_id?: (string | null);
};

export type JobPublic = {
    customer: string;
    part_type: string;
    quantity?: number;
    due_date?: (string | null);
    required_materials?: (string | null);
    priority?: number;
    special_instructions?: (string | null);
    factory_id?: (string | null);
    customer_order_id?: (string | null);
    id: string;
    status: JobStatus;
    missing_info?: (string | null);
    suggested_priority?: (number | null);
    created_at?: (string | null);
};

export type JobsPublic = {
    data: Array<JobPublic>;
    count: number;
};

export type JobStatus = 'intake' | 'approved' | 'scheduled' | 'in_production' | 'complete' | 'cancelled';

export type KnowledgeBaseCreate = {
    name: string;
    description?: (string | null);
    content?: string;
};

export type KnowledgeBasePublic = {
    name: string;
    description?: (string | null);
    content?: string;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type KnowledgeBasesPublic = {
    data: Array<KnowledgeBasePublic>;
    count: number;
};

export type KnowledgeBaseUpdate = {
    name?: (string | null);
    description?: (string | null);
    content?: (string | null);
};

export type KnowledgeDocumentCreate = {
    title: string;
    kind?: DocumentKind;
    machine_id?: (string | null);
    tags?: (string | null);
    content: string;
};

export type KnowledgeDocumentPublic = {
    id: string;
    title: string;
    kind: DocumentKind;
    machine_id?: (string | null);
    tags?: (string | null);
    created_at?: (string | null);
};

export type KnowledgeDocumentsPublic = {
    data: Array<KnowledgeDocumentPublic>;
    count: number;
};

export type LinePublic = {
    name: string;
    status?: LineStatus;
    factory_id: string;
    id: string;
    created_at?: (string | null);
};

export type LinesPublic = {
    data: Array<LinePublic>;
    count: number;
};

export type LineStatus = 'running' | 'idle' | 'down' | 'maintenance';

export type MachineConfigurationCreate = {
    machine_id: string;
    speed?: number;
    temperature?: number;
    pressure?: number;
    feed_rate?: number;
    tooling_profile?: (string | null);
    material_type?: (string | null);
};

export type MachineConfigurationPublic = {
    machine_id: string;
    speed?: number;
    temperature?: number;
    pressure?: number;
    feed_rate?: number;
    tooling_profile?: (string | null);
    material_type?: (string | null);
    id: string;
    version: number;
    is_current: boolean;
    is_recommended: boolean;
    approved: boolean;
    performance_delta: number;
    created_at?: (string | null);
};

export type MachineConfigurationsPublic = {
    data: Array<MachineConfigurationPublic>;
    count: number;
};

export type MachineHealthScorePublic = {
    machine_id: string;
    score?: number;
    fault_frequency?: number;
    vibration_trend?: number;
    temperature_trend?: number;
    missed_maintenance?: number;
    production_interruptions?: number;
    downtime_risk?: number;
    id: string;
    created_at?: (string | null);
};

export type MachinePublic = {
    code: string;
    name: string;
    machine_type?: MachineType;
    manufacturer?: (string | null);
    model?: (string | null);
    factory_id: string;
    line_id?: (string | null);
    pos_x?: number;
    pos_z?: number;
    id: string;
    status: MachineStatus;
    maintenance_state: MaintenanceState;
    health_score: number;
    runtime_hours: number;
    last_fault_code?: (string | null);
    created_at?: (string | null);
};

export type MachinesPublic = {
    data: Array<MachinePublic>;
    count: number;
};

export type MachineStatus = 'running' | 'idle' | 'fault' | 'maintenance' | 'offline';

export type MachineType = 'cnc_mill' | 'robotic_arm' | 'hydraulic_press' | 'other';

export type MaintenanceState = 'ok' | 'due_soon' | 'overdue' | 'in_progress';

export type MaintenanceTicketDetail = {
    code: string;
    title: string;
    machine_id?: (string | null);
    alert_id?: (string | null);
    incident_id?: (string | null);
    severity?: string;
    status?: string;
    what_happened?: string;
    executive_summary?: string;
    operator_detail?: string;
    remediation?: string;
    sop_id?: (string | null);
    sop_anchor?: (string | null);
    suggested_window_days?: number;
    id: string;
    machine_code?: (string | null);
    acknowledged_by?: (string | null);
    acknowledged_at?: (string | null);
    acknowledged_tz?: (string | null);
    created_at?: (string | null);
    machine_name?: (string | null);
    sop_code?: (string | null);
    incident_title?: (string | null);
    parts?: Array<TicketPartPublic>;
    logs?: Array<TicketLogPublic>;
};

export type MaintenanceTicketPublic = {
    code: string;
    title: string;
    machine_id?: (string | null);
    alert_id?: (string | null);
    incident_id?: (string | null);
    severity?: string;
    status?: string;
    what_happened?: string;
    executive_summary?: string;
    operator_detail?: string;
    remediation?: string;
    sop_id?: (string | null);
    sop_anchor?: (string | null);
    suggested_window_days?: number;
    id: string;
    machine_code?: (string | null);
    acknowledged_by?: (string | null);
    acknowledged_at?: (string | null);
    acknowledged_tz?: (string | null);
    created_at?: (string | null);
};

export type MaintenanceTicketsPublic = {
    data: Array<MaintenanceTicketPublic>;
    count: number;
};

export type MaterialReorderPublic = {
    sku: string;
    inventory_item_id?: (string | null);
    status?: string;
    quantity?: number;
    reason?: (string | null);
    machine_code?: (string | null);
    line?: (string | null);
    scheduled_for?: (string | null);
    id: string;
    signed_off_by?: (string | null);
    signed_off_at?: (string | null);
    created_at?: (string | null);
};

export type MaterialReordersPublic = {
    data: Array<MaterialReorderPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OeeMetricPublic = {
    line_id: string;
    machine_id?: (string | null);
    shift?: string;
    availability?: number;
    performance?: number;
    quality?: number;
    oee?: number;
    throughput?: number;
    downtime_minutes?: number;
    scrap_rate?: number;
    rework_rate?: number;
    id: string;
    created_at?: (string | null);
};

export type OeeMetricsPublic = {
    data: Array<OeeMetricPublic>;
    count: number;
};

export type OrderStage = 'received' | 'scheduled' | 'in_production' | 'inspection' | 'complete' | 'shipped';

/**
 * Payload for the local-environment-only user factory endpoint.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductionRunPublic = {
    line_id: string;
    machine_id?: (string | null);
    job_id?: (string | null);
    shift?: string;
    planned_units?: number;
    actual_units?: number;
    scrap_units?: number;
    rework_units?: number;
    downtime_minutes?: number;
    id: string;
    created_at?: (string | null);
};

export type ProductionRunsPublic = {
    data: Array<ProductionRunPublic>;
    count: number;
};

export type PurchaseOrderPublic = {
    po_number: string;
    supplier_id?: (string | null);
    customer_order_id?: (string | null);
    job_id?: (string | null);
    inventory_item_id?: (string | null);
    amount?: number;
    id: string;
    status: PurchaseOrderStatus;
    shop_floor_ready: boolean;
    created_at?: (string | null);
};

export type PurchaseOrdersPublic = {
    data: Array<PurchaseOrderPublic>;
    count: number;
};

export type PurchaseOrderStatus = 'draft' | 'open' | 'received' | 'closed';

export type QuoteCreate = {
    customer: string;
    part_type: string;
    quantity?: number;
    material_cost?: number;
    labor_cost?: number;
    machine_time_cost?: number;
    rush_premium?: number;
    rush?: boolean;
};

export type QuotePublic = {
    customer: string;
    part_type: string;
    quantity?: number;
    material_cost?: number;
    labor_cost?: number;
    machine_time_cost?: number;
    rush_premium?: number;
    rush?: boolean;
    id: string;
    estimated_price: number;
    margin_estimate: number;
    timeline_days: number;
    risk_flags?: (string | null);
    status: QuoteStatus;
    created_at?: (string | null);
};

export type QuotesPublic = {
    data: Array<QuotePublic>;
    count: number;
};

export type QuoteStatus = 'draft' | 'sent' | 'approved' | 'rejected';

export type RcaRecordCreate = {
    root_cause: string;
    corrective_actions?: (string | null);
    timeline_note?: (string | null);
};

export type RcaRecordPublic = {
    incident_id: string;
    root_cause: string;
    corrective_actions?: (string | null);
    timeline_note?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type RcaRecordsPublic = {
    data: Array<RcaRecordPublic>;
    count: number;
};

export type RecommendationPublic = {
    machine_id?: (string | null);
    line_id?: (string | null);
    category?: string;
    title: string;
    detail?: (string | null);
    confidence?: number;
    id: string;
    status: RecommendationStatus;
    outcome_impact?: (number | null);
    created_at?: (string | null);
};

export type RecommendationsPublic = {
    data: Array<RecommendationPublic>;
    count: number;
};

export type RecommendationStatus = 'pending' | 'accepted' | 'rejected';

/**
 * Operator action on a single reorder, posted from the Supply Chain page.
 */
export type ReorderActionRequest = {
    sku: string;
    action: string;
    quantity?: number;
    reason?: (string | null);
    machine_code?: (string | null);
    line?: (string | null);
    scheduled_for?: (string | null);
    inventory_item_id?: (string | null);
};

/**
 * Operator confirmation for the confirm-before-seed gate: the fingerprint
 * and phrase must match the reviewed plan exactly, or nothing runs.
 */
export type SeedConfirmRequest = {
    plan_id: string;
    fingerprint: string;
    /**
     * Must equal the confirmation phrase shown on the plan
     */
    confirmation_phrase: string;
    tables?: (Array<(string)> | null);
};

export type Severity = 'low' | 'medium' | 'high' | 'critical';

/**
 * Cinematic camera directive for the Factory Simulation. After ForgeAI
 * answers on the simulation page, the scene reads this to fly to / follow the
 * entities the answer is about (the "Simulation Tool").
 */
export type SimFocus = {
    mode?: string;
    machine_ids?: Array<(string)>;
    follow_forklift?: boolean;
    label?: string;
};

export type SopDetailPublic = {
    code: string;
    title: string;
    category?: string;
    entity_type?: string;
    machine_id?: (string | null);
    summary?: string;
    revision?: string;
    id: string;
    created_at?: (string | null);
    machine_code?: (string | null);
    sections?: Array<SopSectionPublic>;
};

export type SopPublic = {
    code: string;
    title: string;
    category?: string;
    entity_type?: string;
    machine_id?: (string | null);
    summary?: string;
    revision?: string;
    id: string;
    created_at?: (string | null);
};

export type SopSectionPublic = {
    sop_id: string;
    anchor: string;
    order_index?: number;
    title: string;
    body?: string;
    id: string;
};

export type SopSectionUpdate = {
    anchor: string;
    title?: (string | null);
    body?: (string | null);
};

export type SopsPublic = {
    data: Array<SopPublic>;
    count: number;
};

export type SopUpdate = {
    title?: (string | null);
    summary?: (string | null);
    sections?: Array<SopSectionUpdate>;
};

export type SourceRef = {
    document_id: string;
    title: string;
    kind: string;
    snippet?: string;
    code?: (string | null);
    anchor?: (string | null);
};

export type SupplierPublic = {
    name: string;
    status?: SupplierStatus;
    lead_time_days?: number;
    contact?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

export type SupplierStatus = 'ok' | 'delayed' | 'at_risk';

export type SyncDirection = 'inbound' | 'outbound';

export type SyncEventPublic = {
    entity_type: string;
    entity_id?: (string | null);
    direction?: SyncDirection;
    status?: SyncStatus;
    detail?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type SyncEventsPublic = {
    data: Array<SyncEventPublic>;
    count: number;
};

/**
 * Scope for an operator-triggered ad hoc sync (INC-012) — restricted to
 * contracted cadences/tables, never arbitrary source objects.
 */
export type SyncRequest = {
    cadences?: Array<(string)>;
    tables?: (Array<(string)> | null);
};

export type SyncStatus = 'success' | 'failed' | 'pending';

export type TableSyncRequest = {
    table: string;
};

export type TelemetryEventCreate = {
    machine_id: string;
    temperature?: number;
    vibration?: number;
    cycle_time?: number;
    runtime_hours?: number;
    fault_code?: (string | null);
    power_draw?: number;
    line_status?: LineStatus;
    maintenance_state?: MaintenanceState;
};

export type TelemetryEventPublic = {
    machine_id: string;
    temperature?: number;
    vibration?: number;
    cycle_time?: number;
    runtime_hours?: number;
    fault_code?: (string | null);
    power_draw?: number;
    line_status?: LineStatus;
    maintenance_state?: MaintenanceState;
    id: string;
    created_at?: (string | null);
};

export type TelemetryEventsPublic = {
    data: Array<TelemetryEventPublic>;
    count: number;
};

export type TicketAcknowledge = {
    note?: (string | null);
    tz?: (string | null);
};

export type TicketLogPublic = {
    id: string;
    kind: string;
    author_email?: (string | null);
    message: string;
    tz?: (string | null);
    created_at?: (string | null);
};

export type TicketNote = {
    message: string;
    tz?: (string | null);
};

export type TicketPartPublic = {
    id: string;
    name: string;
    qty_needed: number;
    inventory_item_id?: (string | null);
    sku?: (string | null);
    on_hand?: number;
    unit?: string;
    lead_time_days?: number;
    supplier_name?: (string | null);
    supplier_status?: (string | null);
    needed_by?: (string | null);
    order_by?: (string | null);
    in_stock?: boolean;
    shortfall?: number;
};

export type TicketReference = {
    code: string;
    kind: string;
    id: string;
    title: string;
};

export type TicketStatusUpdate = {
    status: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    customer_id?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    customer_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Assignable roles; each maps onto the site-wide tier ladder
 * (app/core/features.py). Stored as a plain varchar, so extending this
 * enum is additive — no migration (column default stays `operator`).
 */
export type UserRole = 'user' | 'admin' | 'operator' | 'maintenance' | 'planner' | 'customer' | 'leadership' | 'developer' | 'beta_client';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    customer_id?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkOrderCreate = {
    machine_id: string;
    fault_type: string;
    severity?: Severity;
    recommended_task: string;
    required_skill?: (string | null);
    suggested_due_date?: (string | null);
    source_alert_id?: (string | null);
    priority?: number;
};

export type WorkOrderPublic = {
    machine_id: string;
    fault_type: string;
    severity?: Severity;
    recommended_task: string;
    required_skill?: (string | null);
    suggested_due_date?: (string | null);
    source_alert_id?: (string | null);
    priority?: number;
    id: string;
    status: WorkOrderStatus;
    fiix_sync_state: FiixSyncState;
    fiix_id?: (string | null);
    created_at?: (string | null);
};

export type WorkOrdersPublic = {
    data: Array<WorkOrderPublic>;
    count: number;
};

export type WorkOrderStatus = 'draft' | 'approved' | 'rejected' | 'in_progress' | 'completed';

export type AlertsReadAlertsData = {
    limit?: number;
    skip?: number;
    status?: (AlertStatus | null);
};

export type AlertsReadAlertsResponse = (AlertsPublic);

export type AlertsAcknowledgeAlertData = {
    alertId: string;
};

export type AlertsAcknowledgeAlertResponse = (AlertPublic);

export type AlertsResolveAlertData = {
    alertId: string;
};

export type AlertsResolveAlertResponse = (AlertPublic);

export type AskAiAskData = {
    requestBody: AskRequest;
};

export type AskAiAskResponse = (AskResponse);

export type AskAiForgeData = {
    requestBody: AskRequest;
};

export type AskAiForgeResponse = (ForgeResponse);

export type AskAiListDocumentsResponse = (KnowledgeDocumentsPublic);

export type AskAiIngestDocumentData = {
    requestBody: KnowledgeDocumentCreate;
};

export type AskAiIngestDocumentResponse = (KnowledgeDocumentPublic);

export type AskAiListSessionsResponse = (Array<AskaiSessionPublic>);

export type AskAiListKnowledgeBasesResponse = (KnowledgeBasesPublic);

export type AskAiCreateKnowledgeBaseData = {
    requestBody: KnowledgeBaseCreate;
};

export type AskAiCreateKnowledgeBaseResponse = (KnowledgeBasePublic);

export type AskAiUpdateKnowledgeBaseData = {
    kbId: string;
    requestBody: KnowledgeBaseUpdate;
};

export type AskAiUpdateKnowledgeBaseResponse = (KnowledgeBasePublic);

export type AskAiDeleteKnowledgeBaseData = {
    kbId: string;
};

export type AskAiDeleteKnowledgeBaseResponse = (Message);

export type AskAiSyncKnowledgeBasesResponse = (Message);

export type CommandCenterReadFactoriesResponse = (FactoriesPublic);

export type CommandCenterReadLinesResponse = (LinesPublic);

export type CommandCenterFactoryKpisResponse = (unknown);

export type CommandCenterCommandCenterResponse = (unknown);

export type CommandCenterMetricsResponse = (unknown);

export type CustomerMyOrdersResponse = (CustomerOrdersPublic);

export type CustomerMyOrderData = {
    orderId: string;
};

export type CustomerMyOrderResponse = (CustomerOrderPublic);

export type CustomerCustomerAskData = {
    requestBody: AskRequest;
};

export type CustomerCustomerAskResponse = (AskResponse);

export type CustomerEscalateData = {
    requestBody: EscalationCreate;
};

export type CustomerEscalateResponse = (EscalationPublic);

export type CustomerListEscalationsResponse = (EscalationsPublic);

export type CustomerRespondEscalationData = {
    escalationId: string;
    requestBody: HumanResponse;
};

export type CustomerRespondEscalationResponse = (EscalationPublic);

export type DataPlatformPlatformHealthResponse = ({
    [key: string]: unknown;
});

export type DataPlatformReplicationTablesResponse = ({
    [key: string]: unknown;
});

export type DataPlatformReplicationRunsData = {
    limit?: number;
};

export type DataPlatformReplicationRunsResponse = ({
    [key: string]: unknown;
});

export type DataPlatformFreshnessResponse = ({
    [key: string]: unknown;
});

export type DataPlatformReconciliationResultsData = {
    limit?: number;
};

export type DataPlatformReconciliationResultsResponse = ({
    [key: string]: unknown;
});

export type DataPlatformRunDiscoveryResponse = (DiscoveryResponse);

export type DataPlatformGetSeedPlanResponse = ({
    [key: string]: unknown;
});

export type DataPlatformConfirmAndSeedData = {
    requestBody: SeedConfirmRequest;
};

export type DataPlatformConfirmAndSeedResponse = ({
    [key: string]: unknown;
});

export type DataPlatformTriggerSyncData = {
    requestBody: SyncRequest;
};

export type DataPlatformTriggerSyncResponse = ({
    [key: string]: unknown;
});

export type DataPlatformSyncEstimateData = {
    table: string;
};

export type DataPlatformSyncEstimateResponse = ({
    [key: string]: unknown;
});

export type DataPlatformTableSyncStatusResponse = ({
    [key: string]: unknown;
});

export type DataPlatformTriggerTableSyncData = {
    requestBody: TableSyncRequest;
};

export type DataPlatformTriggerTableSyncResponse = ({
    [key: string]: unknown;
});

export type DatasourcesReadTableData = {
    limit?: number;
    name: string;
};

export type DatasourcesReadTableResponse = (unknown);

export type DatasourcesExportSnapshotResponse = (unknown);

export type DatasourcesImportSnapshotData = {
    formData: Body_datasources_import_snapshot;
};

export type DatasourcesImportSnapshotResponse = (unknown);

export type FactoryIntelligenceSubmitInspectionData = {
    requestBody: InspectionCreate;
};

export type FactoryIntelligenceSubmitInspectionResponse = (InspectionPublic);

export type FactoryIntelligenceReadInspectionsData = {
    limit?: number;
};

export type FactoryIntelligenceReadInspectionsResponse = (InspectionsPublic);

export type FactoryIntelligenceReadDefectsData = {
    limit?: number;
};

export type FactoryIntelligenceReadDefectsResponse = (DefectsPublic);

export type FactoryIntelligenceCorrelateDefectData = {
    defectId: string;
};

export type FactoryIntelligenceCorrelateDefectResponse = (unknown);

export type FactoryIntelligenceReadOeeData = {
    limit?: number;
};

export type FactoryIntelligenceReadOeeResponse = (OeeMetricsPublic);

export type FactoryIntelligenceReadTrendsData = {
    limit?: number;
};

export type FactoryIntelligenceReadTrendsResponse = (ProductionRunsPublic);

export type FactoryIntelligenceReadConfigsResponse = (MachineConfigurationsPublic);

export type FactoryIntelligenceCreateConfigData = {
    requestBody: MachineConfigurationCreate;
};

export type FactoryIntelligenceCreateConfigResponse = (MachineConfigurationPublic);

export type FactoryIntelligenceApproveConfigData = {
    configId: string;
};

export type FactoryIntelligenceApproveConfigResponse = (MachineConfigurationPublic);

export type FactoryIntelligenceReadRecommendationsResponse = (RecommendationsPublic);

export type FactoryIntelligenceDecideRecommendationData = {
    accept: boolean;
    outcomeImpact?: (number | null);
    recId: string;
};

export type FactoryIntelligenceDecideRecommendationResponse = (RecommendationPublic);

export type FeaturesMyFeaturesResponse = (unknown);

export type IncidentsReadIncidentsResponse = (IncidentsPublic);

export type IncidentsCreateIncidentData = {
    requestBody: IncidentCreate;
};

export type IncidentsCreateIncidentResponse = (IncidentPublic);

export type IncidentsReadRcaData = {
    incidentId: string;
};

export type IncidentsReadRcaResponse = (RcaRecordsPublic);

export type IncidentsCreateRcaData = {
    incidentId: string;
    requestBody: RcaRecordCreate;
};

export type IncidentsCreateRcaResponse = (RcaRecordPublic);

export type IntegrationsStatusResponse = (IntegrationsStatusPublic);

export type IntegrationsEventsData = {
    system?: string;
};

export type IntegrationsEventsResponse = (SyncEventsPublic);

export type IntegrationsSyncErpResponse = (SyncEventsPublic);

export type IntegrationsSyncMesResponse = (SyncEventsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LakeListLakeDatasetsResponse = ({
    [key: string]: unknown;
});

export type LakeReadLakeDatasetData = {
    dataset: string;
    limit?: number;
    offset?: number;
    orderBy?: (string | null);
    orderDir?: string;
};

export type LakeReadLakeDatasetResponse = ({
    [key: string]: unknown;
});

export type LakeListPublishedLoadsData = {
    table?: (string | null);
};

export type LakeListPublishedLoadsResponse = ({
    [key: string]: unknown;
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LogsLogServicesResponse = (unknown);

export type LogsServiceLogsData = {
    limit?: number;
    service: string;
};

export type LogsServiceLogsResponse = (unknown);

export type MachinesReadMachinesData = {
    limit?: number;
    skip?: number;
};

export type MachinesReadMachinesResponse = (MachinesPublic);

export type MachinesReadMachineData = {
    machineId: string;
};

export type MachinesReadMachineResponse = (MachinePublic);

export type MachinesReadTelemetryData = {
    limit?: number;
    machineId: string;
};

export type MachinesReadTelemetryResponse = (TelemetryEventsPublic);

export type MachinesIngestTelemetryData = {
    machineId: string;
    requestBody: TelemetryEventCreate;
};

export type MachinesIngestTelemetryResponse = (TelemetryEventPublic);

export type MachinesReadHealthData = {
    machineId: string;
};

export type MachinesReadHealthResponse = (MachineHealthScorePublic);

export type MachinesAskMachineData = {
    machineId: string;
    requestBody: AskRequest;
};

export type MachinesAskMachineResponse = (AskResponse);

export type PlanningCapacityResponse = (unknown);

export type PlanningSimulateResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ServicesListServicesResponse = (unknown);

export type SopsReadSopsData = {
    category?: (string | null);
    limit?: number;
    machine?: (string | null);
    skip?: number;
};

export type SopsReadSopsResponse = (SopsPublic);

export type SopsReadSopData = {
    ref: string;
};

export type SopsReadSopResponse = (SopDetailPublic);

export type SopsUpdateSopData = {
    ref: string;
    requestBody: SopUpdate;
};

export type SopsUpdateSopResponse = (SopDetailPublic);

export type SupplyChainReadInventoryResponse = (InventoryItemsPublic);

export type SupplyChainReadSuppliersResponse = (SuppliersPublic);

export type SupplyChainReadRisksResponse = (unknown);

export type SupplyChainReadReordersResponse = (MaterialReordersPublic);

export type SupplyChainActOnReorderData = {
    requestBody: ReorderActionRequest;
};

export type SupplyChainActOnReorderResponse = (MaterialReorderPublic);

export type SupplyChainReadPurchaseOrdersResponse = (PurchaseOrdersPublic);

export type SupplyChainReadOrderTrackerData = {
    activeOnly?: boolean;
};

export type SupplyChainReadOrderTrackerResponse = (unknown);

export type SupplyChainReadQuotesResponse = (QuotesPublic);

export type SupplyChainGenerateQuoteData = {
    requestBody: QuoteCreate;
};

export type SupplyChainGenerateQuoteResponse = (QuotePublic);

export type SupplyChainReadJobsResponse = (JobsPublic);

export type SupplyChainCreateJobData = {
    requestBody: JobCreate;
};

export type SupplyChainCreateJobResponse = (JobPublic);

export type SupplyChainIntakeJobData = {
    rawText: string;
};

export type SupplyChainIntakeJobResponse = (JobPublic);

export type SupplyChainApproveJobData = {
    jobId: string;
};

export type SupplyChainApproveJobResponse = (JobPublic);

export type TicketsReadTicketsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type TicketsReadTicketsResponse = (MaintenanceTicketsPublic);

export type TicketsTicketFromIncidentData = {
    incidentId: string;
};

export type TicketsTicketFromIncidentResponse = (MaintenanceTicketDetail);

export type TicketsTicketFromAlertData = {
    alertId: string;
};

export type TicketsTicketFromAlertResponse = (MaintenanceTicketDetail);

export type TicketsTicketsByIncidentResponse = ({
    [key: string]: (string);
});

export type TicketsReadReferencesResponse = (Array<TicketReference>);

export type TicketsReadTicketData = {
    ticketId: string;
};

export type TicketsReadTicketResponse = (MaintenanceTicketDetail);

export type TicketsAcknowledgeTicketData = {
    requestBody: TicketAcknowledge;
    ticketId: string;
};

export type TicketsAcknowledgeTicketResponse = (MaintenanceTicketDetail);

export type TicketsAddNoteData = {
    requestBody: TicketNote;
    ticketId: string;
};

export type TicketsAddNoteResponse = (MaintenanceTicketDetail);

export type TicketsUpdateStatusData = {
    requestBody: TicketStatusUpdate;
    ticketId: string;
};

export type TicketsUpdateStatusResponse = (MaintenanceTicketDetail);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WarehouseListDatasetsResponse = ({
    [key: string]: unknown;
});

export type WarehouseReadDatasetData = {
    dataset: string;
    limit?: number;
    offset?: number;
    orderBy?: (string | null);
    orderDir?: string;
};

export type WarehouseReadDatasetResponse = ({
    [key: string]: unknown;
});

export type WarehouseWarehouseKpisResponse = ({
    [key: string]: unknown;
});

export type WorkOrdersReadWorkOrdersData = {
    limit?: number;
    skip?: number;
};

export type WorkOrdersReadWorkOrdersResponse = (WorkOrdersPublic);

export type WorkOrdersCreateWorkOrderData = {
    requestBody: WorkOrderCreate;
};

export type WorkOrdersCreateWorkOrderResponse = (WorkOrderPublic);

export type WorkOrdersCreateFromAlertData = {
    alertId: string;
};

export type WorkOrdersCreateFromAlertResponse = (WorkOrderPublic);

export type WorkOrdersApproveWorkOrderData = {
    approve?: boolean;
    woId: string;
};

export type WorkOrdersApproveWorkOrderResponse = (WorkOrderPublic);

export type WorkOrdersSyncFiixData = {
    woId: string;
};

export type WorkOrdersSyncFiixResponse = (WorkOrderPublic);