apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartforge.fullname" . }}-backend
  labels:
    {{- include "smartforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "smartforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
