apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartforge.fullname" . }}-config
  labels:
    {{- include "smartforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- include "smartforge.configData" . | nindent 2 }}
